<a href="https://colab.research.google.com/github/Harithapharidas/DataScience/blob/main/Haritha_P_Haridas_of_CO1_NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# program to create an array of all the even integers from 20 to 80
import numpy as np

x=np.arange(20,80,2)
x


array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78])

In [ ]:
#Write a program to create a numpy array and perform element-wise comparison (greater, greater_equal, less than, lesser_equal).
x=np.array([0,2,3,5,8])
y=np.array([1,2,3,5,7])
print(x)
print(y)
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))


[0 2 3 5 8]
[1 2 3 5 7]
[False False False False  True]
[False  True  True  True  True]
[ True False False False False]
[ True  True  True  True False]


In [ ]:
#program to multiply two given arrays of same size
a1=np.arange(1,7).reshape(2,3)
a2=np.arange(4,10).reshape(2,3)
print('\na1=>\n',a1)
print('\na2=>\n',a2)
print('\nProduct\n',np.multiply(a1,a2))


a1=>
 [[1 2 3]
 [4 5 6]]

a2=>
 [[4 5 6]
 [7 8 9]]

Product
 [[ 4 10 18]
 [28 40 54]]


In [ ]:
#Program to save a given array to a text file and load it
x=np.arange(0,9).reshape(3,3)
print('Array is=\n>',x)
np.savetxt('array.txt',x,fmt="%d")

print("\nAfter loading array\n")
print(np.loadtxt('array.txt'))

Array is=
> [[0 1 2]
 [3 4 5]
 [6 7 8]]

After loading array

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
